from setuptools import setup

setup(
    name='TestTask_SKYTRACKING',
    version='0.1',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.attr', 'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.yarl',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli', 'venv.Lib.site-packages.aiohttp',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.psycopg2',
              'venv.Lib.site-packages.psycopg2.tests', 'venv.Lib.site-packages.multidict',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools._vendor', 'venv.Lib.site-packages.setuptools._vendor.packaging',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages.sqlalchemy',
              'venv.Lib.site-packages.sqlalchemy.ext', 'venv.Lib.site-packages.sqlalchemy.ext.declarative',
              'venv.Lib.site-packages.sqlalchemy.orm', 'venv.Lib.site-packages.sqlalchemy.sql',
              'venv.Lib.site-packages.sqlalchemy.util', 'venv.Lib.site-packages.sqlalchemy.event',
              'venv.Lib.site-packages.sqlalchemy.engine', 'venv.Lib.site-packages.sqlalchemy.testing',
              'venv.Lib.site-packages.sqlalchemy.testing.suite', 'venv.Lib.site-packages.sqlalchemy.testing.plugin',
              'venv.Lib.site-packages.sqlalchemy.dialects', 'venv.Lib.site-packages.sqlalchemy.dialects.mssql',
              'venv.Lib.site-packages.sqlalchemy.dialects.mysql', 'venv.Lib.site-packages.sqlalchemy.dialects.oracle',
              'venv.Lib.site-packages.sqlalchemy.dialects.sqlite', 'venv.Lib.site-packages.sqlalchemy.dialects.sybase',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.async_timeout',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='sendhello',
    author_email='',
    description=''
)
